---
title: "replication_Knight_NEW"
author: "Noelle"
date: "2024-04-30"
output: html_document
---

```{r setup, include=FALSE}
library(rmarkdown)
library(knitr)
library(readxl)
library(boot)
library(tidyverse)
library(pROC)
library(stats)
library(broom)
library(openxlsx)
library(gridExtra)
library(gtsummary)
library(Hmisc)
library(psych)
library(corrplot)
library(ggsignif)
library(ggpubr)
library(lm.beta)

knight <- as.data.frame(read_xlsx("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ALL.xlsx"))
colnames(knight)[colnames(knight) == "AMYLOID.x"] <- "AMYLOID"
colnames(knight)[colnames(knight) == "sex.x"] <- "sex"
colnames(knight)[colnames(knight) == "AGE.x"] <- "AGE"
colnames(knight)[colnames(knight) == "EDUC.x"] <- "EDUC"

colnames(knight)[colnames(knight) == "ptau217lilly_z.x"] <- "ptau217lilly_z"
colnames(knight)[colnames(knight) == "ptau217msd_z.x"] <- "ptau217msd_z"
colnames(knight)[colnames(knight) == "ptau217ratio_z.x"] <- "ptau217ratio_z"
colnames(knight)[colnames(knight) == "ptauab42_z.x"] <- "ptauab42_z"
colnames(knight)[colnames(knight) == "ptau181_z.x"] <- "ptau181_z"
```

```{r table Knight, echo=F}
knight$apoebin <- ifelse(grepl("4", knight$apoe.x), 1, 0)
tabs <- knight %>% select(AGE, sex, EDUC,
                          race.x, cdr.x.x, dx1.x.x, L_Ab42_AB40.x, CSF_10.x, apoebin,Gcogn_z_cu, plasma_217_occupancy.x, plasma_ptau217_conc.x, Plasma_ptau217_pgml_Lilly.x, SUVR.x, LUMI_ptauab42.x, LUMIPULSE_CSF_pTau.x)

tabs$mmse_score <- as.numeric(tabs$mmse_score)
tabs$apoebin <- as.factor(tabs$apoebin)

library(gtsummary)
table <- tabs %>% tbl_summary(type = all_continuous() ~ "continuous2",
                      statistic = list(
                        all_continuous()~ c("{mean} ({sd})",
                                            "{min}, {max}"),
                        all_categorical() ~ "{n} / {N} ({p}%)"
                      ),
                      digits = all_continuous()~2)
table
```

#Amyloid-PET logistic models
```{r AUC AB-PET, echo=F}
model1ab <- glm(AMYLOID ~ scale(ptau217lilly_z) + scale(AGE) + sex, data = knight, family = binomial)
model2ab <- glm(AMYLOID ~ scale(ptau217msd_z) + scale(AGE) + sex, data = knight, family = binomial)
model3ab <- glm(AMYLOID ~ scale(ptau217ratio_z) + scale(AGE) + sex, data = knight, family = binomial)
model4ab <- glm(AMYLOID ~ scale(ptauab42_z) + scale(AGE) + sex, data = knight, family = binomial)
model5ab <- glm(AMYLOID ~ scale(ptau181_z) + scale(AGE) + sex, data = knight, family = binomial)

predicted_probabilities1ab <- predict(model1ab, newdata=knight, type = "response")
predicted_probabilities2ab <- predict(model2ab, newdata=knight, type = "response")
predicted_probabilities3ab <- predict(model3ab, newdata=knight, type = "response")
predicted_probabilities4ab <- predict(model4ab, newdata=knight, type = "response")
predicted_probabilities5ab <- predict(model5ab, newdata=knight, type = "response")

actual_labels <- knight$AMYLOID
roc_lilly = pROC::roc(actual_labels, predicted_probabilities1ab)     
roc_msd = pROC::roc(actual_labels, predicted_probabilities2ab)
roc_msdr = pROC::roc(actual_labels, predicted_probabilities3ab)
roc_ptau181 = pROC::roc(actual_labels, predicted_probabilities5ab)
roc_ptau181ab42 = pROC::roc(actual_labels, predicted_probabilities4ab)

roc_list <- list(roc_msdr, roc_msd, roc_lilly, roc_ptau181ab42, roc_ptau181)
combinations <- combn(roc_list, 2, simplify = F)
delongres <- list()

library(pROC)
for (i in seq_along(combinations)) {
  model1 <- combinations[[i]][[1]]
  model2 <- combinations[[i]][[2]]
  
  # Perform DeLong's test
  res <- roc.test(model1, model2, method = "delong")
  
  long <- data.frame(
    zstat = round(res$statistic,3), 
                                  pval = round(res$p.value,3),
                                  auc1 = res$estimate[1], 
                                  auc2 = res$estimate[2])
        delongres[[length(delongres) + 1]] <- long
}
delongres <- do.call(rbind.data.frame, delongres)
delongres$padj <- round(p.adjust(delongres$pval, method = "fdr"),3)
openxlsx::write.xlsx(delongres,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_DELONG_ABPET.xlsx")

results_roc <- list()
results_auc <- list()
rocs <- c(roc_msdr, roc_msd, roc_lilly, roc_ptau181ab42, roc_ptau181)

coord_msdr <- coords(roc_msdr, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_msdr$auc <- ci.auc(roc_msdr)[2]
coord_msdr$auc_cilow <- ci.auc(roc_msdr)[1]
coord_msdr$auc_cihigh <- ci.auc(roc_msdr)[3]
coord_msdr$model <- "%p-tau217 MSD"

coord_msd <- coords(roc_msd, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_msd$auc <- ci.auc(roc_msd)[2]
coord_msd$auc_cilow <- ci.auc(roc_msd)[1]
coord_msd$auc_cihigh <- ci.auc(roc_msd)[3]
coord_msd$model <- "p-tau217 MSD"

coord_lil <- coords(roc_lilly, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_lil$auc <- ci.auc(roc_lilly)[2]
coord_lil$auc_cilow <- ci.auc(roc_lilly)[1]
coord_lil$auc_cihigh <- ci.auc(roc_lilly)[3]
coord_lil$model <- "p-tau217 Lilly"

coord_ptau181ab42 <- coords(roc_ptau181ab42, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_ptau181ab42$auc <- ci.auc(roc_ptau181ab42)[2]
coord_ptau181ab42$auc_cilow <- ci.auc(roc_ptau181ab42)[1]
coord_ptau181ab42$auc_cihigh <- ci.auc(roc_ptau181ab42)[3]
coord_ptau181ab42$model <- "p-tau181/AB42 Lumipulse"

coord_ptau181 <- coords(roc_ptau181, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_ptau181$auc <- ci.auc(roc_ptau181)[2]
coord_ptau181$auc_cilow <- ci.auc(roc_ptau181)[1]
coord_ptau181$auc_cihigh <- ci.auc(roc_ptau181)[3]
coord_ptau181$model <- "p-tau181 Lumipulse"

results_auc <- rbind(coord_msdr, coord_msd, coord_lil, coord_ptau181ab42, coord_ptau181)
openxlsx::write.xlsx(results_auc,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AUC.xlsx")
```

```{r AUC ABPET bootstrapping + plots, echo=F}
datafr <- knight
actual_labels <- datafr$AMYLOID
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "ptauab42_z", "ptau181_z")

bsab <- function(data, indices, ref, comp) {
  d <- data[indices, ]
  actual_labels <- d$AMYLOID
  
  fml1_string <- paste("AMYLOID ~ scale(AGE) + sex +", ref)
  formula1 <- as.formula(fml1_string)
  model1 <- glm(formula1, data = d, family = binomial)
  pred_prob1 <- predict(model1, newdata = d, type = "response")
  roc_curve1 <- pROC::roc(actual_labels, pred_prob1, quiet=T)
  auc_model1 <- ci.auc(roc_curve1)[2]
  
  fml2_string <- paste("AMYLOID ~ scale(AGE) + sex +", comp)
  formula2 <- as.formula(fml2_string)
  model2 <- glm(formula2, data = d, family = binomial)
  pred_prob2 <- predict(model2, newdata = d, type = "response")
  roc_curve2 <- pROC::roc(actual_labels, pred_prob2, quiet=T)
  auc_model2 <- ci.auc(roc_curve2)[2]
  
  difference_auc <- roc_curve1$auc - roc_curve2$auc
  
  return(c(difference_auc, auc_model1, auc_model2))
}

results_auc_ab <- list()
for (i in 1:(length(biomarkers)-1)) {
  zref <- biomarkers[i]
  
  for (j in (i + 1):length(biomarkers)) {
    zcomp <- biomarkers[j]
    
    #hist(boot_results$t[,1])
    set.seed(123)
    boot_results <- boot(data = datafr, 
                         statistic = bsab, 
                         R = 1000, 
                         ref = zref,
                         comp = zcomp)
    bootstrap_replicates <- boot_results$t
    boot_aucdiff <- boot_results$t0[1]
    results_underH0_aucdiff <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
    boot_pvalue_aucdiff <- mean(abs(results_underH0_aucdiff) >= abs(boot_aucdiff))
    ci1_auc <- quantile(boot_results$t[,2], c(0.025, 0.975))
    ci2_auc <- quantile(boot_results$t[,3], c(0.025, 0.975))
    cidiff_aucdiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
    results_auc_ab[[paste(zref, zcomp, sep = "_")]] <- data.frame(
      comp = paste(zref,zcomp, sep = "_"),
      variable1 = zref,
      variable2 = zcomp,
      AUC1 = round((boot_results$t0[2]),7),
      aucci1_lower = round(ci1_auc[1],7),
      aucci1_upper = round(ci1_auc[2],7),
      AUC2 = round((boot_results$t0[3]),7),
      aucci2_lower = round(ci2_auc[1],7),
      aucci2_upper = round(ci2_auc[2],7), 
      pvalue_auc = boot_pvalue_aucdiff,
      aucdiff = round((boot_results$t0[1]),7),
      cilow_aucdiff = round(cidiff_aucdiff[1],7),
      cihigh_aucdiff=round(cidiff_aucdiff[2],7),
      plotname = biomarkers[i]
    )
  }
}

final_auc_ab <- do.call(rbind.data.frame, results_auc_ab)
final_auc_ab$padj_auc <- round(p.adjust(final_auc_ab$pvalue_auc, method = "fdr"),3)

openxlsx::write.xlsx(final_auc_ab,file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_bootstrapsAUC_ABPET.xlsx")

test <- head(final_auc_ab, 1)
test <- test %>% select(variable1,AUC1, aucci1_lower, aucci1_upper)
colnames(test)[colnames(test) == "variable1"] <- "variable2"
colnames(test)[colnames(test) == "AUC1"] <- "AUC2"
colnames(test)[colnames(test) == "aucci1_lower"] <- "aucci2_lower"
colnames(test)[colnames(test) == "aucci1_upper"] <- "aucci2_upper"

xx <- final_auc_ab %>%
  select(-variable1,-AUC1, -aucci1_lower, -aucci1_upper)
xx <- head(xx,4)
plot_data <- bind_rows(test, xx)
plot_data$plotcolors = c("1", "2", "3", "4", "5")
plot_data$Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "CSF p-tau181/Aβ42 Lumipulse", "CSF p-tau181 Lumipulse"))
colnames(plot_data)[colnames(plot_data) == "AUC2"] <- "AUC"
colnames(plot_data)[colnames(plot_data) == "aucci2_lower"] <- "AUC_CIlow"
colnames(plot_data)[colnames(plot_data) == "aucci2_upper"] <- "AUC_CIhigh"

plot_data$table_s <-sprintf("%.3f (%.3f,%.3f)", plot_data$AUC, plot_data$AUC_CIlow, plot_data$AUC_CIhigh)
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AB_AUC_table.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 4, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 4, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


AUC <- ggplot(data = plot_data, aes(x = factor(Assay,levels = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")), y = AUC,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$AUC[4], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = AUC_CIlow, ymax = AUC_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", AUC)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")) + 
  scale_y_continuous(limits=c(0.7,1),breaks = seq(0.7, 1, by=0.05), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "AUC Aβ-PET",x = element_blank(),y = "TES()") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=10, face="bold"))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ABPET_ROC.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```

```{r accuracy comparisons AB PET, echo=F}
bsab <- function(data, indices, ref, comp) {
  d <- data[indices, ]
  
  # Model 1
  fml1_string <- paste("AMYLOID ~ scale(AGE) + sex +", ref)
  formula1 <- as.formula(fml1_string)
  model1 <- glm(formula1, data = d, family = binomial)
  pred_prob1 <- predict(model1, newdata = d, type = "response")
  
  # Model 2
  fml2_string <- paste("AMYLOID ~ scale(AGE) + sex +", comp)
  formula2 <- as.formula(fml2_string)
  model2 <- glm(formula2, data = d, family = binomial)
  pred_prob2 <- predict(model2, newdata = d, type = "response")
  
  # Calculate Youden's index and corresponding threshold for Model 1
  roc_curve1 <- roc(d$AMYLOID, pred_prob1, quiet=T)
  coordm1 <- coords(roc_curve1, "best", best.method = "youden")
  threshold1 <- coordm1$threshold
  
  # Apply threshold to predict binary outcome
  pred_bin1 <- ifelse(pred_prob1 > threshold1, 1, 0)
  
  # Calculate Youden's index and corresponding threshold for Model 2
  roc_curve2 <- roc(d$AMYLOID, pred_prob2, quiet=T)
  coordm2 <- coords(roc_curve2, "best", best.method = "youden")
  threshold2 <- coordm2$threshold
  
  # Apply threshold to predict binary outcome
  pred_bin2 <- ifelse(pred_prob2 > threshold2, 1, 0)
  
  # Calculate confusion matrices
  cm1 <- table(d$AMYLOID, pred_bin1)
  cm2 <- table(d$AMYLOID, pred_bin2)
  
  # Calculate accuracy
  accuracy_m1 <- sum(diag(cm1)) / sum(cm1)
  accuracy_m2 <- sum(diag(cm2)) / sum(cm2)
  
  # Calculate differences
  difference_acc <- accuracy_m1 - accuracy_m2
  
  return(c(difference_acc, accuracy_m1, accuracy_m2))
}

biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "ptauab42_z", "ptau181_z")


results_auc_ab_acc <- list()
library(pROC)

for (i in 1:(length(biomarkers)-1)) {
  zref <- biomarkers[i]
  
  for (j in (i + 1):length(biomarkers)) {
    zcomp <- biomarkers[j]
    
    #hist(boot_results$t[,1])
    set.seed(123)
    boot_results <- boot(data = datafr, 
                         statistic = bsab, 
                         R = 1000, 
                         ref = zref,
                         comp = zcomp)
    bootstrap_replicates <- boot_results$t
    
    boot_accdiff <- boot_results$t0[1]
    results_underH0_accdiff <- bootstrap_replicates[,1] - mean(bootstrap_replicates[1])
    boot_pvalue_accdiff <- mean(abs(results_underH0_accdiff) >= abs(boot_accdiff))
    ci1_acc <- quantile(boot_results$t[,2], c(0.025, 0.975))
    ci2_acc <- quantile(boot_results$t[,3], c(0.025, 0.975))
    cidiff_accdiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
    results_auc_ab_acc[[paste(zref, zcomp, sep = "_")]] <- data.frame(
      comp = paste(zref,zcomp, sep = "_"),
      variable1 = zref,
      variable2 = zcomp,
      Accuracy1 = round((boot_results$t0[2]),7),
      accci1_lower = round(ci1_acc[1],7),
      accci1_upper = round(ci1_acc[2],7),
      Accuracy2 = round((boot_results$t0[3]),7),
      accci2_lower = round(ci2_acc[1],7),
      accci2_upper = round(ci2_acc[2],7),
      pvalue_accuracy = boot_pvalue_accdiff,
      accdiff = round((boot_results$t0[1]),7),
      cilow_accdiff = round(cidiff_accdiff[1],7),
      cihigh_accdiff=round(cidiff_accdiff[2],7),
      plotname = biomarkers[i]
    )
  }
}

final_acc_ab <- do.call(rbind.data.frame, results_auc_ab_acc)
final_acc_ab$padj_acc <- round(p.adjust(final_acc_ab$pvalue_acc, method = "fdr"),3)
openxlsx::write.xlsx(final_acc_ab,file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_Accuracy_ABPET.xlsx")


test <- head(final_acc_ab, 1)
test <- test %>% select(variable1,Accuracy1, accci1_lower, accci1_upper)
colnames(test)[colnames(test) == "variable1"] <- "variable2"
colnames(test)[colnames(test) == "Accuracy1"] <- "Accuracy2"
colnames(test)[colnames(test) == "accci1_lower"] <- "accci2_lower"
colnames(test)[colnames(test) == "accci1_upper"] <- "accci2_upper"

xx <- final_acc_ab %>%
  select(-variable1,-Accuracy1, -accci1_lower, -accci1_upper)
xx <- head(xx,4)
plot_data <- bind_rows(test, xx)
plot_data$plotcolors = c("1", "2", "3", "4", "5")
plot_data$Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "CSF p-tau181/Aβ42 Lumipulse", "CSF p-tau181 Lumipulse"))
colnames(plot_data)[colnames(plot_data) == "Accuracy2"] <- "ACC"
colnames(plot_data)[colnames(plot_data) == "accci2_lower"] <- "ACC_CIlow"
colnames(plot_data)[colnames(plot_data) == "accci2_upper"] <- "ACC_CIhigh"

plot_data$table_s <-sprintf("%.3f (%.3f,%.3f)", plot_data$ACC, plot_data$ACC_CIlow, plot_data$ACC_CIhigh)
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AB_Acc_table.xlsx")


map_to_color <- function(x) {
  ifelse(x >= 4, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 4, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)

ACC <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")),y = ACC,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$ACC[4], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = ACC_CIlow, ymax = ACC_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", ACC)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")) + 
  scale_y_continuous(limits=c(0.7,1),breaks = seq(0.7, 1, by=0.05), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(y = "TEST()",
       x = element_blank(),
       title = "Accuracy Aβ-PET") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA), 
        plot.title = element_text(hjust=0.5, size=10, face="bold"))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ABPET_Accuracy.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")

```

#Linear models (including cognition)
```{r linear models, echo=F}
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "ptauab42_z", "ptau181_z")
adpathology <- c("SUVR.x","Gcogn_z_cu")

list_model<-vector(mode="list", length=length(biomarkers)*length(adpathology))
results_linear <- list()

count = 1

library(broom)
for (j in 1:length(adpathology)){
    for(i in 1:length(biomarkers)){
  
    formula_string <- paste("scale(",adpathology[j],") ~ scale(", biomarkers[i], ")+ scale(AGE) + sex + scale(EDUC)", collapse = " ")
    formula <- as.formula(formula_string)    
    model <- lm(formula, data = knight)
   
    model_summary <- tidy(model, conf.int = TRUE, conf.level = 0.95)
    sample_size <- length(model$residuals)
    rsqr <- summary(model)$adj.r.squared
    model_summary$SampleSize <- sample_size
    model_summary$R2 <- rsqr
    
    list_model[[count]] <- model_summary
    names(list_model)[count] <- paste(adpathology[j], biomarkers[i], sep = "_")

    count=count+1

      temp_linear <- data.frame(
      Model = paste(adpathology[j], biomarkers[i], sep = "_"),
      Estimate = sprintf("%.3f (%.3f)", model_summary$estimate[2], model_summary$std.error[2]),
      pvalue = round((model_summary$p.value[2]),3),
      CI_Lower = round((model_summary$conf.low[2]),3),
      CI_Upper = round((model_summary$conf.high[2]),3),
      Sample_size = round((model_summary$SampleSize[2]),3),
      R2 = round((model_summary$R2[2]),3),
      Estimateplot = round((model_summary$estimate[2]),3),
      stringsAsFactors = FALSE
    )
    results_linear <- rbind(results_linear, temp_linear)
  }
}

view(results_linear)
openxlsx::write.xlsx(results_linear,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_linear.xlsx")
```

```{r R2 AB, echo=F}
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "ptauab42_z", "ptau181_z")
R2diff_AB <- function(data, indices, ref, comp) {
      d <- data[indices,] # allows boot to select sample #indices = 1:365
      fml1=as.formula(paste("scale(SUVR.x) ~ scale(",ref,") + scale(AGE) + sex"))
      mdl1_boot=lm(fml1, data=d)
      mdl1_sum = summary(mdl1_boot)
      fml2=as.formula(paste("scale(SUVR.x) ~ scale(",comp,") + scale(AGE) + sex"))
      mdl2_boot=lm(fml2, data=d)
      mdl2_sum = summary(mdl2_boot)
      r2_m1 <- mdl1_sum$adj.r.squared
      r2_m2 <- mdl2_sum$adj.r.squared
      diff <- r2_m1 - r2_m2
      return(c(diff, r2_m1, r2_m2))
 }

results_r2_ab <- list()

for (i in 1:(length(biomarkers)-1)) {
      zref <- biomarkers[i]

  for (j in (i + 1):length(biomarkers)) {
      zcomp <- biomarkers[j]
  
        #hist(boot_results$t[,1])
        set.seed(123)
        boot_results <- boot(data = knight, 
                             statistic = R2diff_AB, 
                             R = 1000, 
                             ref = zref,
                             comp = zcomp)
        bootstrap_replicates <- boot_results$t
        bootxxx <- boot_results$t0[1]
        results_underH0 <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
        boot_pvalue <- mean(abs(results_underH0) >= abs(bootxxx))
        ci1 <- quantile(boot_results$t[,2], c(0.025, 0.975))
        ci2 <- quantile(boot_results$t[,3], c(0.025, 0.975))
        cidiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
        
      results_r2_ab[[paste(zref, zcomp, sep = "_")]] <- data.frame(
        comp = paste(zref,zcomp, sep = "_"),
        variable1 = zref,
        variable2 = zcomp,
        R2diff = round((boot_results$t0[1]),7),
        R2group1 = round((boot_results$t0[2]),7),
        R2group2 = round((boot_results$t0[3]),7),
        pvalue = boot_pvalue,
        cidiff_low = round(cidiff[1],7),
        cidiff_high = round(cidiff[2],7),
        ci1_lower = round(ci1[1],7),
        ci1_upper = round(ci1[2],7),
        ci2_lower = round(ci2[1],7),
        ci2_upper = round(ci2[2],7), 
        plotname = biomarkers[i]
        )
  }
}

finalr2_ab <- do.call(rbind.data.frame, results_r2_ab)
finalr2_ab$padj <- round(p.adjust(finalr2_ab$pvalue, method = "fdr"),3)
view(finalr2_ab)
openxlsx::write.xlsx(finalr2_ab,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_AB.xlsx")

plot_data <- data.frame(
  Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "p-tau181/AB42 Lumipulse", "p-tau181 Lumipulse")),
  unique_valuesR2 = unique(c(finalr2_ab$R2group1, finalr2_ab$R2group2)),
  unique_valuesR2_CIlow = unique(c(finalr2_ab$ci1_lower, finalr2_ab$ci2_lower)),
  unique_valuesR2_CIhigh = unique(c(finalr2_ab$ci1_upper, finalr2_ab$ci2_upper)),
  variable2 = finalr2_ab$variable2,
  padj = finalr2_ab$padj
)
plot_data$plotcolors = c("1", "2", "3", "4", "5")
plot_data$tables = sprintf("%.3f (%.3f,%.3f)", plot_data$unique_valuesR2, plot_data$unique_valuesR2_CIlow, plot_data$unique_valuesR2_CIhigh)
plot_data <- plot_data[0:5,]
#openxlsx::write.xlsx(plot_data,
                    # file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight replication/Knight_R2comp_AB_table.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 4, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 4, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


p <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")),y = unique_valuesR2,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$unique_valuesR2[4], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = unique_valuesR2_CIlow, ymax = unique_valuesR2_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", unique_valuesR2)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")) + 
  scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "Aβ-PET", x = element_blank(),y = "Adj. R2 (95% CI)") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=12, face="bold"), 
        axis.title.x = element_text(size=11))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ABPET_R2.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```

```{r R2 cog, echo=F}
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "ptauab42_z", "ptau181_z")
R2diff_mmse <- function(data, indices, ref, comp) {
      d <- data[indices,] # allows boot to select sample #indices = 1:365
      fml1=as.formula(paste("scale(Gcogn_z_cu) ~ scale(",ref,") + scale(AGE) + sex + scale(EDUC)"))
      mdl1_boot=lm(fml1, data=d)
      mdl1_sum = summary(mdl1_boot)
      fml2=as.formula(paste("scale(Gcogn_z_cu) ~ scale(",comp,") + scale(AGE) + sex + scale(EDUC)"))
      mdl2_boot=lm(fml2, data=d)
      mdl2_sum = summary(mdl2_boot)
      r2_m1 <- mdl1_sum$adj.r.squared
      r2_m2 <- mdl2_sum$adj.r.squared
      diff <- r2_m1 - r2_m2
      return(c(diff, r2_m1, r2_m2))
 }

results_r2_cog <- list()

library(boot)
for (i in 1:(length(biomarkers)-1)) {
      zref <- biomarkers[i]

  for (j in (i + 1):length(biomarkers)) {
      zcomp <- biomarkers[j]
  
        #hist(boot_results$t[,1])
        set.seed(123)
        boot_results <- boot(data = knight, 
                             statistic = R2diff_mmse, 
                             R = 1000, 
                             ref = zref,
                             comp = zcomp)
        bootstrap_replicates <- boot_results$t
        bootxxx <- boot_results$t0[1]
        results_underH0 <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
        boot_pvalue <- mean(abs(results_underH0) >= abs(bootxxx))
        ci1 <- quantile(boot_results$t[,2], c(0.025, 0.975))
        ci2 <- quantile(boot_results$t[,3], c(0.025, 0.975))
        cidiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
        
      results_r2_cog[[paste(zref, zcomp, sep = "_")]] <- data.frame(
        comp = paste(zref,zcomp, sep = "_"),
        variable1 = zref,
        variable2 = zcomp,
        R2diff = round((boot_results$t0[1]),7),
        R2group1 = round((boot_results$t0[2]),7),
        R2group2 = round((boot_results$t0[3]),7),
        pvalue = boot_pvalue,
        cidiff_low = round(cidiff[1],7),
        cidiff_high = round(cidiff[2],7),
        ci1_lower = round(ci1[1],7),
        ci1_upper = round(ci1[2],7),
        ci2_lower = round(ci2[1],7),
        ci2_upper = round(ci2[2],7), 
        plotname = biomarkers[i]
        )
  }
}

finalr2_cog <- do.call(rbind.data.frame, results_r2_cog)
finalr2_cog$padj <- round(p.adjust(finalr2_cog$pvalue, method = "fdr"),3)
view(finalr2_cog)
openxlsx::write.xlsx(finalr2_cog,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_globalcog.xlsx")

plot_data <- data.frame(
  Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "p-tau181/AB42 Lumipulse", "p-tau181 Lumipulse")),
  unique_valuesR2 = unique(c(finalr2_cog$R2group1, finalr2_cog$R2group2)),
  unique_valuesR2_CIlow = unique(c(finalr2_cog$ci1_lower, finalr2_cog$ci2_lower)),
  unique_valuesR2_CIhigh = unique(c(finalr2_cog$ci1_upper, finalr2_cog$ci2_upper)),
  variable2 = finalr2_cog$variable2,
  padj = finalr2_cog$padj
)
plot_data$plotcolors = c("1", "2", "3", "4", "5")
plot_data$tables = sprintf("%.3f (%.3f,%.3f)", plot_data$unique_valuesR2, plot_data$unique_valuesR2_CIlow, plot_data$unique_valuesR2_CIhigh)
plot_data <- plot_data[0:5,]
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_cog_table.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 4, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 4, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


p <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")),y = unique_valuesR2,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$unique_valuesR2[4], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = unique_valuesR2_CIlow, ymax = unique_valuesR2_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", unique_valuesR2)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")) + 
  scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "Global Cognitive Composite", x = element_blank(),y = "Adj. R2 (95% CI)") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=12, face="bold"), 
        axis.title.x = element_text(size=11))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_globalcog_R2.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```

#Replication with Alamar data

```{r setup Alamar, include=FALSE}
library(readxl)
library(tidyverse)
library(dplyr)

knight <- as.data.frame(read_xlsx("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ALL_alamar.xlsx"))
colnames(knight)[colnames(knight) == "AMYLOID.x"] <- "AMYLOID"
colnames(knight)[colnames(knight) == "sex.x"] <- "sex"
colnames(knight)[colnames(knight) == "AGE.x"] <- "AGE"
colnames(knight)[colnames(knight) == "EDUC.x"] <- "EDUC"

colnames(knight)[colnames(knight) == "ptau217lilly_z.x"] <- "ptau217lilly_z"
colnames(knight)[colnames(knight) == "ptau217msd_z.x"] <- "ptau217msd_z"
colnames(knight)[colnames(knight) == "ptau217ratio_z.x"] <- "ptau217ratio_z"
colnames(knight)[colnames(knight) == "ptauab42_z.x"] <- "ptauab42_z"
colnames(knight)[colnames(knight) == "ptau181_z.x"] <- "ptau181_z"

```

```{r AUC AB-PET, Alamar, echo=F}

library(pROC)
library(stats)
library(broom)
library(openxlsx)
model1ab <- glm(AMYLOID ~ scale(ptau217lilly_z) + scale(AGE) + sex, data = knight, family = binomial)
model2ab <- glm(AMYLOID ~ scale(ptau217msd_z) + scale(AGE) + sex, data = knight, family = binomial)
model3ab <- glm(AMYLOID ~ scale(ptau217ratio_z) + scale(AGE) + sex, data = knight, family = binomial)
model4ab <- glm(AMYLOID ~ scale(alamar_z) + scale(AGE) + sex, data = knight, family = binomial)
model5ab <- glm(AMYLOID ~ scale(ptauab42_z) + scale(AGE) + sex, data = knight, family = binomial)
model6ab <- glm(AMYLOID ~ scale(ptau181_z) + scale(AGE) + sex, data = knight, family = binomial)

predicted_probabilities1ab <- predict(model1ab, newdata=knight, type = "response")
predicted_probabilities2ab <- predict(model2ab, newdata=knight, type = "response")
predicted_probabilities3ab <- predict(model3ab, newdata=knight, type = "response")
predicted_probabilities4ab <- predict(model4ab, newdata=knight, type = "response")
predicted_probabilities5ab <- predict(model5ab, newdata=knight, type = "response")
predicted_probabilities6ab <- predict(model6ab, newdata=knight, type = "response")

actual_labels <- knight$AMYLOID
roc_lilly = pROC::roc(actual_labels, predicted_probabilities1ab)     
roc_msd = pROC::roc(actual_labels, predicted_probabilities2ab)
roc_msdr = pROC::roc(actual_labels, predicted_probabilities3ab)
roc_al = pROC::roc(actual_labels, predicted_probabilities4ab)
roc_ptau181 = pROC::roc(actual_labels, predicted_probabilities6ab)
roc_ptau181ab42 = pROC::roc(actual_labels, predicted_probabilities5ab)


roc_list <- list(roc_msdr, roc_msd, roc_lilly, roc_al, roc_ptau181ab42, roc_ptau181)
combinations <- combn(roc_list, 2, simplify = F)
delongres <- list()

library(pROC)
for (i in seq_along(combinations)) {
  model1 <- combinations[[i]][[1]]
  model2 <- combinations[[i]][[2]]
  
  # Perform DeLong's test
  res <- roc.test(model1, model2, method = "delong")
  
  long <- data.frame(
    zstat = round(res$statistic,3), 
                                  pval = round(res$p.value,3),
                                  auc1 = res$estimate[1], 
                                  auc2 = res$estimate[2])
        delongres[[length(delongres) + 1]] <- long
  # Print or store the results
  #print(paste("Comparison between", names(roc_list)[i], "and", names(roc_list)[j]))
  #print(res)
}
delongres <- do.call(rbind.data.frame, delongres)
delongres$padj <- round(p.adjust(delongres$pval, method = "fdr"),3)
openxlsx::write.xlsx(delongres,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_DELONG_ABPET_Alamar.xlsx")


results_roc <- list()
results_auc <- list()
rocs <- c(roc_msdr, roc_msd, roc_lilly, roc_ptau181ab42, roc_ptau181)

coord_msdr <- coords(roc_msdr, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_msdr$auc <- ci.auc(roc_msdr)[2]
coord_msdr$auc_cilow <- ci.auc(roc_msdr)[1]
coord_msdr$auc_cihigh <- ci.auc(roc_msdr)[3]
coord_msdr$model <- "%p-tau217 MSD"

coord_msd <- coords(roc_msd, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_msd$auc <- ci.auc(roc_msd)[2]
coord_msd$auc_cilow <- ci.auc(roc_msd)[1]
coord_msd$auc_cihigh <- ci.auc(roc_msd)[3]
coord_msd$model <- "p-tau217 MSD"

coord_lil <- coords(roc_lilly, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_lil$auc <- ci.auc(roc_lilly)[2]
coord_lil$auc_cilow <- ci.auc(roc_lilly)[1]
coord_lil$auc_cihigh <- ci.auc(roc_lilly)[3]
coord_lil$model <- "p-tau217 Lilly"


coord_al <- coords(roc_al, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_al$auc <- ci.auc(roc_al)[2]
coord_al$auc_cilow <- ci.auc(roc_al)[1]
coord_al$auc_cihigh <- ci.auc(roc_al)[3]
coord_al$model <- "p-tau217 Alamar"


coord_ptau181ab42 <- coords(roc_ptau181ab42, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_ptau181ab42$auc <- ci.auc(roc_ptau181ab42)[2]
coord_ptau181ab42$auc_cilow <- ci.auc(roc_ptau181ab42)[1]
coord_ptau181ab42$auc_cihigh <- ci.auc(roc_ptau181ab42)[3]
coord_ptau181ab42$model <- "p-tau181/AB42 Lumipulse"

coord_ptau181 <- coords(roc_ptau181, "best", best.method="youden", ret=c("threshold","specificity", "sensitivity", "accuracy", "npv","ppv", "tn", "tp", "fn", "fp"))
coord_ptau181$auc <- ci.auc(roc_ptau181)[2]
coord_ptau181$auc_cilow <- ci.auc(roc_ptau181)[1]
coord_ptau181$auc_cihigh <- ci.auc(roc_ptau181)[3]
coord_ptau181$model <- "p-tau181 Lumipulse"

results_auc <- rbind(coord_msdr, coord_msd, coord_lil, coord_al, coord_ptau181ab42, coord_ptau181)

openxlsx::write.xlsx(results_auc,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AUC_Alamar.xlsx")
```

```{r AUC ABPET bootstrapping + plots, Alamar, echo=F}
library(pROC)
library(boot)
datafr <- knight
actual_labels <- datafr$AMYLOID

biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "alamar_z", "ptauab42_z", "ptau181_z")

bsab <- function(data, indices, ref, comp) {
  d <- data[indices, ]
  actual_labels <- d$AMYLOID
  
  fml1_string <- paste("AMYLOID ~ scale(AGE) + sex +", ref)
  formula1 <- as.formula(fml1_string)
  model1 <- glm(formula1, data = d, family = binomial)
  pred_prob1 <- predict(model1, newdata = d, type = "response")
  roc_curve1 <- pROC::roc(actual_labels, pred_prob1, quiet=T)
  auc_model1 <- ci.auc(roc_curve1)[2]
  
  fml2_string <- paste("AMYLOID ~ scale(AGE) + sex +", comp)
  formula2 <- as.formula(fml2_string)
  model2 <- glm(formula2, data = d, family = binomial)
  pred_prob2 <- predict(model2, newdata = d, type = "response")
  roc_curve2 <- pROC::roc(actual_labels, pred_prob2, quiet=T)
  auc_model2 <- ci.auc(roc_curve2)[2]
  
  difference_auc <- roc_curve1$auc - roc_curve2$auc
  
  return(c(difference_auc, auc_model1, auc_model2))
}

library(boot)
results_auc_ab <- list()
for (i in 1:(length(biomarkers)-1)) {
  zref <- biomarkers[i]
  
  for (j in (i + 1):length(biomarkers)) {
    zcomp <- biomarkers[j]
    
    #hist(boot_results$t[,1])
    set.seed(123)
    boot_results <- boot(data = datafr, 
                         statistic = bsab, 
                         R = 1000, 
                         ref = zref,
                         comp = zcomp)
    bootstrap_replicates <- boot_results$t
    boot_aucdiff <- boot_results$t0[1]
    results_underH0_aucdiff <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
    boot_pvalue_aucdiff <- mean(abs(results_underH0_aucdiff) >= abs(boot_aucdiff))
    ci1_auc <- quantile(boot_results$t[,2], c(0.025, 0.975))
    ci2_auc <- quantile(boot_results$t[,3], c(0.025, 0.975))
    cidiff_aucdiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
    results_auc_ab[[paste(zref, zcomp, sep = "_")]] <- data.frame(
      comp = paste(zref,zcomp, sep = "_"),
      variable1 = zref,
      variable2 = zcomp,
      AUC1 = round((boot_results$t0[2]),7),
      aucci1_lower = round(ci1_auc[1],7),
      aucci1_upper = round(ci1_auc[2],7),
      AUC2 = round((boot_results$t0[3]),7),
      aucci2_lower = round(ci2_auc[1],7),
      aucci2_upper = round(ci2_auc[2],7), 
      pvalue_auc = boot_pvalue_aucdiff,
      aucdiff = round((boot_results$t0[1]),7),
      cilow_aucdiff = round(cidiff_aucdiff[1],7),
      cihigh_aucdiff=round(cidiff_aucdiff[2],7),
      plotname = biomarkers[i]
    )
  }
}

final_auc_ab <- do.call(rbind.data.frame, results_auc_ab)
final_auc_ab$padj_auc <- round(p.adjust(final_auc_ab$pvalue_auc, method = "fdr"),3)

openxlsx::write.xlsx(final_auc_ab,file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_bootstrapsAUC_ABPET_Alamar.xlsx")

test <- head(final_auc_ab, 1)
test <- test %>% select(variable1,AUC1, aucci1_lower, aucci1_upper)
colnames(test)[colnames(test) == "variable1"] <- "variable2"
colnames(test)[colnames(test) == "AUC1"] <- "AUC2"
colnames(test)[colnames(test) == "aucci1_lower"] <- "aucci2_lower"
colnames(test)[colnames(test) == "aucci1_upper"] <- "aucci2_upper"

xx <- final_auc_ab %>%
  select(-variable1,-AUC1, -aucci1_lower, -aucci1_upper)
xx <- head(xx,5)
plot_data <- bind_rows(test, xx)
plot_data$plotcolors = c("1", "2", "3", "4", "5", "6")
plot_data$Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "p-tau217 Alamar", "CSF p-tau181/Aβ42 Lumipulse", "CSF p-tau181 Lumipulse"))
colnames(plot_data)[colnames(plot_data) == "AUC2"] <- "AUC"
colnames(plot_data)[colnames(plot_data) == "aucci2_lower"] <- "AUC_CIlow"
colnames(plot_data)[colnames(plot_data) == "aucci2_upper"] <- "AUC_CIhigh"

plot_data$table_s <-sprintf("%.3f (%.3f,%.3f)", plot_data$AUC, plot_data$AUC_CIlow, plot_data$AUC_CIhigh)
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AB_AUC_table_Alamar.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 5, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 5, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


AUC <- ggplot(data = plot_data, aes(x = factor(Assay,levels = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse",
                                                                "p-tau217 Alamar",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")), y = AUC,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$AUC[5], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = AUC_CIlow, ymax = AUC_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", AUC)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse","p-tau217 Alamar",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")) + 
  scale_y_continuous(limits=c(0.7,1),breaks = seq(0.7, 1, by=0.05), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "AUC Aβ-PET",x = element_blank(),y = "TES()") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=10, face="bold"))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ABPET_ROC_Alamar.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```

```{r accuracy comparisons AB PET Alamar, echo=F}
bsab <- function(data, indices, ref, comp) {
  d <- data[indices, ]
  
  # Model 1
  fml1_string <- paste("AMYLOID ~ scale(AGE) + sex +", ref)
  formula1 <- as.formula(fml1_string)
  model1 <- glm(formula1, data = d, family = binomial)
  pred_prob1 <- predict(model1, newdata = d, type = "response")
  
  # Model 2
  fml2_string <- paste("AMYLOID ~ scale(AGE) + sex +", comp)
  formula2 <- as.formula(fml2_string)
  model2 <- glm(formula2, data = d, family = binomial)
  pred_prob2 <- predict(model2, newdata = d, type = "response")
  
  # Calculate Youden's index and corresponding threshold for Model 1
  roc_curve1 <- roc(d$AMYLOID, pred_prob1, quiet=T)
  coordm1 <- coords(roc_curve1, "best", best.method = "youden")
  threshold1 <- coordm1$threshold
  
  # Apply threshold to predict binary outcome
  pred_bin1 <- ifelse(pred_prob1 > threshold1, 1, 0)
  
  # Calculate Youden's index and corresponding threshold for Model 2
  roc_curve2 <- roc(d$AMYLOID, pred_prob2, quiet=T)
  coordm2 <- coords(roc_curve2, "best", best.method = "youden")
  threshold2 <- coordm2$threshold
  
  # Apply threshold to predict binary outcome
  pred_bin2 <- ifelse(pred_prob2 > threshold2, 1, 0)
  
  # Calculate confusion matrices
  cm1 <- table(d$AMYLOID, pred_bin1)
  cm2 <- table(d$AMYLOID, pred_bin2)
  
  # Calculate accuracy
  accuracy_m1 <- sum(diag(cm1)) / sum(cm1)
  accuracy_m2 <- sum(diag(cm2)) / sum(cm2)
  
  # Calculate differences
  difference_acc <- accuracy_m1 - accuracy_m2
  
  return(c(difference_acc, accuracy_m1, accuracy_m2))
}

biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "alamar_z", "ptauab42_z", "ptau181_z")


results_auc_ab_acc <- list()
library(pROC)

for (i in 1:(length(biomarkers)-1)) {
  zref <- biomarkers[i]
  
  for (j in (i + 1):length(biomarkers)) {
    zcomp <- biomarkers[j]
    
    #hist(boot_results$t[,1])
    set.seed(123)
    boot_results <- boot(data = datafr, 
                         statistic = bsab, 
                         R = 1000, 
                         ref = zref,
                         comp = zcomp)
    bootstrap_replicates <- boot_results$t
    
    boot_accdiff <- boot_results$t0[1]
    results_underH0_accdiff <- bootstrap_replicates[,1] - mean(bootstrap_replicates[1])
    boot_pvalue_accdiff <- mean(abs(results_underH0_accdiff) >= abs(boot_accdiff))
    ci1_acc <- quantile(boot_results$t[,2], c(0.025, 0.975))
    ci2_acc <- quantile(boot_results$t[,3], c(0.025, 0.975))
    cidiff_accdiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
    results_auc_ab_acc[[paste(zref, zcomp, sep = "_")]] <- data.frame(
      comp = paste(zref,zcomp, sep = "_"),
      variable1 = zref,
      variable2 = zcomp,
      Accuracy1 = round((boot_results$t0[2]),7),
      accci1_lower = round(ci1_acc[1],7),
      accci1_upper = round(ci1_acc[2],7),
      Accuracy2 = round((boot_results$t0[3]),7),
      accci2_lower = round(ci2_acc[1],7),
      accci2_upper = round(ci2_acc[2],7),
      pvalue_accuracy = boot_pvalue_accdiff,
      accdiff = round((boot_results$t0[1]),7),
      cilow_accdiff = round(cidiff_accdiff[1],7),
      cihigh_accdiff=round(cidiff_accdiff[2],7),
      plotname = biomarkers[i]
    )
  }
}

final_acc_ab <- do.call(rbind.data.frame, results_auc_ab_acc)
final_acc_ab$padj_acc <- round(p.adjust(final_acc_ab$pvalue_acc, method = "fdr"),3)
#final_auc_tau$padj_accuracy <- round(p.adjust(final_auc_tau$pvalue_accuracy, method = "fdr"),3)

openxlsx::write.xlsx(final_acc_ab,file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_Accuracy_ABPET_Alamar.xlsx")


test <- head(final_acc_ab, 1)
test <- test %>% select(variable1,Accuracy1, accci1_lower, accci1_upper)
colnames(test)[colnames(test) == "variable1"] <- "variable2"
colnames(test)[colnames(test) == "Accuracy1"] <- "Accuracy2"
colnames(test)[colnames(test) == "accci1_lower"] <- "accci2_lower"
colnames(test)[colnames(test) == "accci1_upper"] <- "accci2_upper"

xx <- final_acc_ab %>%
  select(-variable1,-Accuracy1, -accci1_lower, -accci1_upper)
xx <- head(xx,5)
plot_data <- bind_rows(test, xx)
plot_data$plotcolors = c("1", "2", "3", "4", "5", "6")
plot_data$Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Alamar","p-tau217 Lilly", "CSF p-tau181/Aβ42 Lumipulse", "CSF p-tau181 Lumipulse"))
colnames(plot_data)[colnames(plot_data) == "Accuracy2"] <- "ACC"
colnames(plot_data)[colnames(plot_data) == "accci2_lower"] <- "ACC_CIlow"
colnames(plot_data)[colnames(plot_data) == "accci2_upper"] <- "ACC_CIhigh"

plot_data$table_s <-sprintf("%.3f (%.3f,%.3f)", plot_data$ACC, plot_data$ACC_CIlow, plot_data$ACC_CIhigh)
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_AB_Acc_table_Alamar.xlsx")


map_to_color <- function(x) {
  ifelse(x >= 5, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 5, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)

ACC <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse","p-tau217 Alamar","p-tau217 Lilly","p-tau217 WashU","%p-tau217 WashU")),y = ACC,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$ACC[5], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = ACC_CIlow, ymax = ACC_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", ACC)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("CSF p-tau181 Lumipulse","CSF p-tau181/Aβ42 Lumipulse","p-tau217 Alamar",
                                                                "p-tau217 Lilly","p-tau217 WashU",
                                                                "%p-tau217 WashU")) + 
  scale_y_continuous(limits=c(0.7,1),breaks = seq(0.7, 1, by=0.05), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(y = "TEST()",
       x = element_blank(),
       title = "Accuracy Aβ-PET") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA), 
        plot.title = element_text(hjust=0.5, size=10, face="bold"))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/ABPET_Accuracy_Alamar.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")

```

```{r linear models Alamar, echo=F}
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "alamar_z", "ptauab42_z", "ptau181_z")
adpathology <- c("SUVR.x","Gcogn_z_cu")

list_model<-vector(mode="list", length=length(biomarkers)*length(adpathology))
results_linear <- list()

count = 1

library(broom)
for (j in 1:length(adpathology)){
    for(i in 1:length(biomarkers)){
  
    formula_string <- paste("scale(",adpathology[j],") ~ scale(", biomarkers[i], ")+ scale(AGE) + sex + scale(EDUC)", collapse = " ")
    formula <- as.formula(formula_string)    
    model <- lm(formula, data = knight)
   
    model_summary <- tidy(model, conf.int = TRUE, conf.level = 0.95)
    sample_size <- length(model$residuals)
    rsqr <- summary(model)$adj.r.squared
    model_summary$SampleSize <- sample_size
    model_summary$R2 <- rsqr
    
    list_model[[count]] <- model_summary
    names(list_model)[count] <- paste(adpathology[j], biomarkers[i], sep = "_")

    count=count+1

      temp_linear <- data.frame(
      Model = paste(adpathology[j], biomarkers[i], sep = "_"),
      Estimate = sprintf("%.3f (%.3f)", model_summary$estimate[2], model_summary$std.error[2]),
      pvalue = round((model_summary$p.value[2]),3),
      CI_Lower = round((model_summary$conf.low[2]),3),
      CI_Upper = round((model_summary$conf.high[2]),3),
      Sample_size = round((model_summary$SampleSize[2]),3),
      R2 = round((model_summary$R2[2]),3),
      Estimateplot = round((model_summary$estimate[2]),3),
      stringsAsFactors = FALSE
    )
    results_linear <- rbind(results_linear, temp_linear)
  }
}

view(results_linear)
openxlsx::write.xlsx(results_linear,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_linear_Alamar.xlsx")
```

```{r R2 AB Alamar, echo=F}

biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "alamar_z", "ptauab42_z", "ptau181_z")
R2diff_AB <- function(data, indices, ref, comp) {
      d <- data[indices,] # allows boot to select sample #indices = 1:365
      fml1=as.formula(paste("scale(SUVR.x) ~ scale(",ref,") + scale(AGE) + sex"))
      mdl1_boot=lm(fml1, data=d)
      mdl1_sum = summary(mdl1_boot)
      fml2=as.formula(paste("scale(SUVR.x) ~ scale(",comp,") + scale(AGE) + sex"))
      mdl2_boot=lm(fml2, data=d)
      mdl2_sum = summary(mdl2_boot)
      r2_m1 <- mdl1_sum$adj.r.squared
      r2_m2 <- mdl2_sum$adj.r.squared
      diff <- r2_m1 - r2_m2
      return(c(diff, r2_m1, r2_m2))
 }

results_r2_ab <- list()

for (i in 1:(length(biomarkers)-1)) {
      zref <- biomarkers[i]

  for (j in (i + 1):length(biomarkers)) {
      zcomp <- biomarkers[j]
  
        #hist(boot_results$t[,1])
        set.seed(123)
        boot_results <- boot(data = knight, 
                             statistic = R2diff_AB, 
                             R = 1000, 
                             ref = zref,
                             comp = zcomp)
        bootstrap_replicates <- boot_results$t
        bootxxx <- boot_results$t0[1]
        results_underH0 <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
        boot_pvalue <- mean(abs(results_underH0) >= abs(bootxxx))
        #ci1 <- boot.ci(boot_results, type = "norm", index = c(2))
        #ci2 <- boot.ci(boot_results, type = "norm", index = c(3))
        ci1 <- quantile(boot_results$t[,2], c(0.025, 0.975))
        ci2 <- quantile(boot_results$t[,3], c(0.025, 0.975))
        cidiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
        
      results_r2_ab[[paste(zref, zcomp, sep = "_")]] <- data.frame(
        comp = paste(zref,zcomp, sep = "_"),
        variable1 = zref,
        variable2 = zcomp,
        R2diff = round((boot_results$t0[1]),7),
        R2group1 = round((boot_results$t0[2]),7),
        R2group2 = round((boot_results$t0[3]),7),
        pvalue = boot_pvalue,
        cidiff_low = round(cidiff[1],7),
        cidiff_high = round(cidiff[2],7),
        ci1_lower = round(ci1[1],7),
        ci1_upper = round(ci1[2],7),
        ci2_lower = round(ci2[1],7),
        ci2_upper = round(ci2[2],7), 
        plotname = biomarkers[i]
        )
  }
}

finalr2_ab <- do.call(rbind.data.frame, results_r2_ab)
finalr2_ab$padj <- round(p.adjust(finalr2_ab$pvalue, method = "fdr"),3)
view(finalr2_ab)
openxlsx::write.xlsx(finalr2_ab,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_AB_Alamar.xlsx")

plot_data <- data.frame(
  Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "p-tau217 Alamar","p-tau181/AB42 Lumipulse", "p-tau181 Lumipulse")),
  unique_valuesR2 = unique(c(finalr2_ab$R2group1, finalr2_ab$R2group2)),
  unique_valuesR2_CIlow = unique(c(finalr2_ab$ci1_lower, finalr2_ab$ci2_lower)),
  unique_valuesR2_CIhigh = unique(c(finalr2_ab$ci1_upper, finalr2_ab$ci2_upper)))
#,variable2 = finalr2_ab$variable2,padj = finalr2_ab$padj)

plot_data$plotcolors = c("1", "2", "3", "4", "5", "6")
plot_data$tables = sprintf("%.3f (%.3f,%.3f)", plot_data$unique_valuesR2, plot_data$unique_valuesR2_CIlow, plot_data$unique_valuesR2_CIhigh)
plot_data <- plot_data[0:6,]
openxlsx::write.xlsx(plot_data,
                    file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_AB_table_alamar.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 5, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 5, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


p <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Alamar","p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")),y = unique_valuesR2,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$unique_valuesR2[5], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = unique_valuesR2_CIlow, ymax = unique_valuesR2_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", unique_valuesR2)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Alamar","p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")) + 
  scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "Aβ-PET", x = element_blank(),y = "Adj. R2 (95% CI)") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=12, face="bold"), 
        axis.title.x = element_text(size=11))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_ABPET_R2_Alamar.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```

```{r R2 cognition Alamar, echo=F}
biomarkers <- c("ptau217ratio_z", "ptau217msd_z", "ptau217lilly_z", "alamar_z", "ptauab42_z", "ptau181_z")
R2diff_mmse <- function(data, indices, ref, comp) {
      d <- data[indices,] # allows boot to select sample #indices = 1:365
      fml1=as.formula(paste("scale(Gcogn_z_cu) ~ scale(",ref,") + scale(AGE) + sex + scale(EDUC)"))
      mdl1_boot=lm(fml1, data=d)
      mdl1_sum = summary(mdl1_boot)
      fml2=as.formula(paste("scale(Gcogn_z_cu) ~ scale(",comp,") + scale(AGE) + sex + scale(EDUC)"))
      mdl2_boot=lm(fml2, data=d)
      mdl2_sum = summary(mdl2_boot)
      r2_m1 <- mdl1_sum$adj.r.squared
      r2_m2 <- mdl2_sum$adj.r.squared
      diff <- r2_m1 - r2_m2
      return(c(diff, r2_m1, r2_m2))
 }

results_r2_cog <- list()

library(boot)
for (i in 1:(length(biomarkers)-1)) {
      zref <- biomarkers[i]

  for (j in (i + 1):length(biomarkers)) {
      zcomp <- biomarkers[j]
  
        #hist(boot_results$t[,1])
        set.seed(123)
        boot_results <- boot(data = knight, 
                             statistic = R2diff_mmse, 
                             R = 1000, 
                             ref = zref,
                             comp = zcomp)
        bootstrap_replicates <- boot_results$t
        bootxxx <- boot_results$t0[1]
        results_underH0 <- bootstrap_replicates[,1] - mean(bootstrap_replicates[,1])
        boot_pvalue <- mean(abs(results_underH0) >= abs(bootxxx))
        #ci1 <- boot.ci(boot_results, type = "norm", index = c(2))
        #ci2 <- boot.ci(boot_results, type = "norm", index = c(3))
        ci1 <- quantile(boot_results$t[,2], c(0.025, 0.975))
        ci2 <- quantile(boot_results$t[,3], c(0.025, 0.975))
        cidiff <- quantile(boot_results$t[,1], c(0.025, 0.975))
    
        
      results_r2_cog[[paste(zref, zcomp, sep = "_")]] <- data.frame(
        comp = paste(zref,zcomp, sep = "_"),
        variable1 = zref,
        variable2 = zcomp,
        R2diff = round((boot_results$t0[1]),7),
        R2group1 = round((boot_results$t0[2]),7),
        R2group2 = round((boot_results$t0[3]),7),
        pvalue = boot_pvalue,
        cidiff_low = round(cidiff[1],7),
        cidiff_high = round(cidiff[2],7),
        ci1_lower = round(ci1[1],7),
        ci1_upper = round(ci1[2],7),
        ci2_lower = round(ci2[1],7),
        ci2_upper = round(ci2[2],7), 
        plotname = biomarkers[i]
        )
  }
}

finalr2_cog <- do.call(rbind.data.frame, results_r2_cog)
finalr2_cog$padj <- round(p.adjust(finalr2_cog$pvalue, method = "fdr"),3)
view(finalr2_cog)
openxlsx::write.xlsx(finalr2_cog,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_globalcog_Alamar.xlsx")

finalr2_cog <- read_xlsx("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_globalcog_Alamar.xlsx")

plot_data <- data.frame(
  Assay = as.factor(c("%p-tau217 WashU", "p-tau217 WashU", "p-tau217 Lilly", "p-tau217 Alamar","p-tau181/AB42 Lumipulse", "p-tau181 Lumipulse")),
  unique_valuesR2 = unique(c(finalr2_cog$R2group1, finalr2_cog$R2group2)),
  unique_valuesR2_CIlow = unique(c(finalr2_cog$ci1_lower, finalr2_cog$ci2_lower)),
  unique_valuesR2_CIhigh = unique(c(finalr2_cog$ci1_upper, finalr2_cog$ci2_upper))
)

plot_data$plotcolors = c("1", "2", "3", "4", "5", "6")
plot_data$tables = sprintf("%.3f (%.3f,%.3f)", plot_data$unique_valuesR2, plot_data$unique_valuesR2_CIlow, plot_data$unique_valuesR2_CIhigh)
plot_data <- plot_data[0:6,]
openxlsx::write.xlsx(plot_data,
                     file="~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_R2comp_cog_table_Alamar.xlsx")

map_to_color <- function(x) {
  ifelse(x >= 5, "#0461BD", "#93003a")  # Change the condition and colors as needed
}

map_to_shape <- function(x) {
  ifelse(x >= 5, "15", "19")  # Change the condition and colors as needed
}

plot_data$color_plot <- map_to_color(plot_data$plotcolors)
plot_data$shape_plot <- map_to_shape(plot_data$plotcolors)
my_shapes <- c(15, 19, 17, 3, 5, 4, 8)


p <- ggplot(data = plot_data, aes(x = factor(Assay, 
                                               levels = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Alamar","p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")),y = unique_valuesR2,color = color_plot,shape = shape_plot)) +
  geom_hline(yintercept = plot_data$unique_valuesR2[4], color = "#0461BD", linetype = "dotted", alpha=0.5) +
  coord_flip() +
  geom_pointrange(aes(ymin = unique_valuesR2_CIlow, ymax = unique_valuesR2_CIhigh),
                  size = 0.6, lwd = 1.25, position = position_dodge(width = 0.2)) +
  geom_text(aes(label = sprintf("%.2f", unique_valuesR2)),
            position = position_dodge(width = 0.75), 
            vjust = -0.5, hjust = -0.25, size = 4) +
  scale_x_discrete(limits = c("p-tau181 Lumipulse", "p-tau181/AB42 Lumipulse", "p-tau217 Alamar","p-tau217 Lilly", "p-tau217 WashU", "%p-tau217 WashU")) + 
  scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  scale_color_identity(guide = "none") +
  scale_shape_manual(values = my_shapes, guide = "none") +
  labs(title = "Global Cognitive Composite", x = element_blank(),y = "Adj. R2 (95% CI)") +
  theme_classic() +
  theme(axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10),
        panel.border = element_rect(linewidth = 0.5, fill = NA),
        plot.title = element_text(hjust=0.5, size=12, face="bold"), 
        axis.title.x = element_text(size=11))

ggsave("~/Documents/Projects/H-2-H plasma ptau217 assays/Knight_globalcog_R2_Alamar.pdf",device = "pdf",width = 125, dpi=500, height = 100, units = "mm")
```
